FROM hyperledger/fabric-cop-runtime:_TAG_
ENV COP_HOME /etc/hyperledger/fabric-cop
RUN mkdir -p $COP_HOME
COPY payload/cop /usr/local/bin
ADD payload/sampleconfig.tar.bz2 $COP_HOME
EXPOSE 8888
CMD cop server start -config $COP_HOME/cop.json
