FROM hyperledger/fabric-ca-runtime:_TAG_
ENV FABRIC_CA_HOME /etc/hyperledger/fabric-ca
RUN mkdir -p $FABRIC_CA_HOME /var/hyperledger/fabric-ca
COPY payload/fabric-ca /usr/local/bin
ADD payload/sampleconfig.tar.bz2 $FABRIC_CA_HOME
EXPOSE 8888
CMD fabric-ca server start -address 0.0.0.0 -config $FABRIC_CA_HOME/config.json
